### ISSUE TITLE
Add trip short name to trip view (on map or list view)

### ISSUE THREAD

**Issue by wkulesza** [OneBusAway/onebusaway-ios#329]
**Summary:** 
When viewing trip details (be it map view or list view), it would be handy to include trip short name (if agency uses it).
In some cases, trips follow different trip patterns (i.e. are shorter and head earlier to depot or are longer and pass through additional stops). If trip short name is provided in GTFS, it could be displayed alongside vehicle id.

**Screenshots:** 
Below is a suggested screenshot, based on purely fictional data.

http://prntscr.com/vt4tc8

**Comment by ualch9** [comment]
> http://prntscr.com/vt4tc8
![download](https://user-images.githubusercontent.com/22162410/100678793-d0357100-3322-11eb-9905-07cdc3f99f22.png)
