### ISSUE TITLE
Retain cycle of unknown cause

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-ios#394]
Discovered while working on #391, reproducible on main branch 45d2fe6. Unsure when this was bug introduced.
Needs additional investigation, reference cycles appears to be closures associated with OBAKitCore.DecodableOperation, but I'm wondering if it's related to OBAListViewItem closures.

Screenshot attached.

![image](https://user-images.githubusercontent.com/22162410/122812074-141fa180-d286-11eb-94db-4091bcafefd9.png)

**Comment by aaronbrethorst** [comment]
I don't think this blocks release.

**Comment by ualch9** [comment]
agreed.

— alan
________________________________
