### ISSUE TITLE
Add setting to show stop number instead of other information on map

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-ios#413]
| Current | Mock |
| -- | -- |
| ![](https://user-images.githubusercontent.com/22162410/125202295-d4662d00-e227-11eb-9df4-49a9dfe3f597.png) | ![mock](https://user-images.githubusercontent.com/22162410/125202573-0035e280-e229-11eb-9f70-6a2caf9b8ce8.png) |

For reference, this is how King County Metro's bus signs look,
![image](https://user-images.githubusercontent.com/22162410/125202593-1cd21a80-e229-11eb-92a9-3d8f4b51e4d5.png)
Image from @\transitrunner (Twitter)

**Comment by aaronbrethorst** [comment]
I'm not generally in favor of adding new settings. They're hard to find, only a small percentage of users will ever enable them, and they increase the likelihood of introducing regressions. Instead, I'd prefer seeing this implemented universally. I think that adding the stop number to the annotation view makes the most sense at this time.

**Comment by aaronbrethorst** [comment]
also, this should be in addition to the route information, not as opposed to.
