### ISSUE TITLE
Add support for migrating stop bookmarks (if anyone complains)

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#441]
Please close this ticket on 12/31/2021 if it has not seen any action by then.

I am intentionally not including support for migrating stop-level bookmarks from classic OBA to OBAKit. I am hoping no one notices or cares. If anyone does, then please fix this. If no one does, then please close this.

**Comment by ualch9** [comment]
this seems important? i personally don't group any of my favorites, although that could be because i constantly delete the app for development.

**Comment by aaronbrethorst** [comment]
@ualch9 this is strictly for stop-level bookmarks, as opposed to route-level bookmarks. If this proves to be a problem and we get complaints, then I'll revisit (and all user data will remain intact, anyway), but I suspect we won't hear a peep about this.
