### ISSUE TITLE
Match OBA Android Firebase Analytics events and user properties

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-ios#457]
Google announced the expansion of the Firebase platform yesterday:
https://firebase.googleblog.com/2016/05/firebase-expands-to-become-unified-app-platform.html

We should take a close look at analytics:
https://firebase.google.com/docs/analytics/

> Firebase Analytics provides unlimited reporting on up to 500 distinct events.

This could potentially help us with our major Google Analytics problem, which is the limit on reported events - we've been around 10x over the limit for some time, and I'm not sure if/how that is affecting our data.

Looks like you can implement Google Analytics and Firebase Analytics side-by-side:
https://support.google.com/analytics/answer/2587086#firebase-ga

We'll probably want to do this and confirm that Firebase seems to work before changing anything with Google Analytics.

We're going to look at this on Android as well - https://github.com/OneBusAway/onebusaway-android/issues/501.  We will keep everyone posted when we make progress there.

**Comment by aaronbrethorst** [comment]
this is finally done!
