### ISSUE TITLE
Missing Languages?

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#464]
Our list of supported languages is:

```
        CFBundleLocalizations:
          - en
          - es
          - it
          - pl
          - zh-Hans
```

But according to the App Store, we only support English and Polish. Gotta get this sorted out, and sooner than later.

![image](https://user-images.githubusercontent.com/2254/129077111-94855d51-e14f-414f-a1a0-afc4192fd504.png)

**Comment by ualch9** [comment]
Just tested and the languages do work once installed, so this seems to be an App Store bug.
