### ISSUE TITLE
Little funky green dots appearing on right side of stop-level bookmarks

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#469]
The big black box is obscuring an OBA user's information. What I want to call your attention to are the little green dots on the right side of some but not all of the stop-level bookmark cells. 

![Untitled-1](https://user-images.githubusercontent.com/2254/129311761-864875ea-abe2-40ea-b022-6e57243095ef.jpg)

**Comment by aaronbrethorst** [comment]
@ualch9 any ideas offhand?

**Comment by ualch9** [comment]
probably cell reuse related. i don't plan on addressing this since its not presenting false information and I need to rebuild BookmarkViewController anyways, OBAListView is too limited in the functionality I want to provide (#481).
