### ISSUE TITLE
Improve "Load More" Button

### ISSUE THREAD

**Issue by roverman** [OneBusAway/onebusaway-ios#475]
**Issue:** 

“Load More” button is large and disconnected from the bus schedule surface

Date and time below “Load More” are confusing to users (from usability test)

Recommendation: 
Consolidate “Load More” into the same surface as the bus schedule, and add down icon for better affordance

~Get rid of date and time associated with “Load More” to avoid user confusion~

Aaron notes: The date/time range was added in a few years back specifically in response to user confusion about routes that run infrequently. Perhaps we can find a way to improve the way it is displayed, but we should not remove it.

![image](https://user-images.githubusercontent.com/68605140/129314750-9a285793-8b35-4172-8816-815cffee6416.png)

**Comment by aaronbrethorst** [comment]
@roverman - I've added some notes to the description for this task. I like most of what's described here, except for getting rid of the date/time range. Perhaps it could be expressed as something like "Showing data for DD HH:MM - HH:MM"?

**Comment by roverman** [comment]
@aaronbrethorst  Sounds good to me, the key is to bring load more button into the same surface as the schedule. So your edit works great, thank you!
