### ISSUE TITLE
App Store "Compatibility" section is wrong

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#488]
It's not clear how one updates these requirements, but they should get fixed...

![image](https://user-images.githubusercontent.com/2254/129637375-de4a86f4-0a0c-461a-867b-4e95c89854d6.png)

**Comment by ualch9** [comment]
I believe App Store will keep the latest compatible version for previous OSes, if that makes sense. 

— alan
