### ISSUE TITLE
Map zooms out of its own accord while user tries to zoom in

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#504]
User feedback:

> Well the new app interface looks really nice, when I am zooming in on an iPhone it often zooms right back out to the full region. Seems to be a bug here. 

```
App Version = 21.3.0
OS Version = 14.7.1
Locale = en
VoiceOver Running = false
Bookmark Count = 0
Location Authorization = authorizedWhenInUse
Region = Tampa Bay
Region ID = 0
Base API URL = https://api.tampa.onebusaway.org/api/
Device = iPhone13,2
```

https://user-images.githubusercontent.com/2254/131010620-5d9b8b36-c0d2-48c4-aba4-c6ce1dcdeaea.mov

**Comment by ualch9** [comment]
I was unable to reproduce the issue. 

The map zooms out to the whole region whenever the OBA region is updated. I suggested to the user to turn off Automatic Region Selection and it seems to have fixed the issue for them. 

I’m guessing there might be a hardware problem with the user’s location services or GPS that’s causing the region to update more frequently than expected.

**Comment by aaronbrethorst** [comment]
thanks, Alan!

**Comment by ualch9** [comment]
As a temporary workaround, the current guidance for users is:

> If this problem is still occurring, please try turning off “Automatically select region,”
> 1. Go to More tab
> 2. Tap on [Region], under the My Location section
> 3. Turn OFF [Automatically select region]
> 4. Select [Tampa Bay] from the region’s list

**Comment by ualch9** [comment]
Issue reproduction steps:
1. Simulate Tampa Bay location on physical device
2. Turn ON [Automatically select region]
3. Zoom in anywhere on the Map
4. Go to Springboard home
5. Reopen OneBusAway
6. Issue: Map zooms out to show the region
