### ISSUE TITLE
`StopViewController` not deallocating, causing random haptic feedback

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#505]
From a user:

> When I have the app open, the haptic feedback seems to just be making random ticks. More so when moving than when still. Other than that, I can’t determine what’s causing it, but it’s sort of annoying.

**Comment by ualch9** [comment]
There is a strong reference somewhere in `StopViewController` preventing deallocation, which is likely causing this random ticking.

**Comment by aaronbrethorst** [comment]
After this gets fixed, we should be sure to undo the change I made in #518
