### ISSUE TITLE
Add support for creating custom regions

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#534]
The old iOS app allowed you to create custom regions within the app. This feature didn't make it over with the rewrite. We should add it back. There should be an "Add Region" button inside of the region picker, which pops up a ~Eureka~ form that lets you specify required information.

**Comment by ualch9** [comment]
since we're writing a new feature, i think we should try a swiftui form instead of eureka.

**Comment by aaronbrethorst** [comment]
@ualch9 sure, ok
