### ISSUE TITLE
Editing a bookmark prompts "Duplicate bookmark"

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-ios#557]
See attached video:

https://user-images.githubusercontent.com/22162410/137218446-b4ecb7e7-cd2c-4a56-9271-cff69e562931.MP4

**Comment by cathy810218** [comment]
Hi Alan! 
If we remove this duplicate bookmark check, then it would not prompt the alert nor duplicate the bookmark.
Though I am not sure if this was intended to be added as an option for duplicating the bookmark.

https://github.com/OneBusAway/onebusaway-ios/blob/9f576f31fe8a273f5418e3c8708e1e1755ee5e42/OBAKit/Bookmarks/EditBookmarkViewController.swift#L219-L228

**Comment by ualch9** [comment]
@cathy810218 yes, that makes sense, i dont believe the intention was to give the user an option to duplicate bookmark. when editing the bookmark, we should not be checking if it is a duplicate. 

if you'd like to tackle this, i can assign you to this issue.

**Comment by cathy810218** [comment]
Okay! I will submit a PR! Thank you.
