### ISSUE TITLE
Alert Details Are Not Available

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-ios#601]
When trying to view the details of an alert, the details are not shown and the window appears cut off or blank.

![image](https://user-images.githubusercontent.com/5028299/176738495-0bdea66b-e6f9-43af-aa59-3369e39b81d7.png)

![image](https://user-images.githubusercontent.com/5028299/176738519-d39d371d-452f-47f6-9ac2-b00e9cead08a.png)

To reproduce the issue, open any alert for San Diego and try to view the details.

**Comment by aaronbrethorst** [comment]
@devinbraun I've fixed this issue and will get a TestFlight build out with it asap.

**Comment by devinbraun** [comment]
@aaronbrethorst Thank you as always!
