### ISSUE TITLE
Update Eureka to address App Store Connect "references non-public selectors" warning

### ISSUE THREAD

**Issue by wkulesza** [OneBusAway/onebusaway-ios#611]
After successfully building (and testing in simulator) a white-label app, following this great guide [https://github.com/OneBusAway/onebusaway-ios/blob/main/Tutorials/WhiteLabel.md](url) - kudos @aaronbrethorst , tried to archive the app and push to testflight.
After it passed tests and got uploaded, this screen showed up:
![obraz](https://user-images.githubusercontent.com/1014296/193339586-25987bbd-1773-4bbd-b368-68f014c418b9.png)

It turned out afterwards, the app did appear in the testflight, so this error didn't block this, but it's good to log it.

**Comment by ualch9** [comment]
Likely caused by https://github.com/xmartlabs/Eureka/issues/2230.

**Comment by ualch9** [comment]
Just did an App Store Connect upload with this change, and this warning no longer appears.
