### ISSUE TITLE
Remove Dark Sky references

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-ios#650]
When clicking in the app for information about the DarkSky weather service, the Dark Sky API states that support will end on 3/31/23.  This is not an in-app message, but a message on the DarkSky Docs website.

**Comment by aaronbrethorst** [comment]
I've actually replaced Dark Sky on the backend. https://github.com/OneBusAway/onebusaway-deep-links/commit/79cbc3acc89870a0394dedadc6a9d03c021289c3

This message should be removed from the OBA app as it's no longer relevant.

**Comment by ualch9** [comment]
Oh neat. I think then we should remove Dark Sky references from the app for 23.2, and continue with #223 when I get the chance.

**Comment by aaronbrethorst** [comment]
Right on, sounds like a good plan @ualch9
