### ISSUE TITLE
No "advanced" option in iOS, but does exist on Android

### ISSUE THREAD

**Issue by Macintosh-Fan** [OneBusAway/onebusaway-ios#679]
I was watching a YouTube video that showed how to connect to a server that runs OneBusAway. I couldn't find the setting on iOS...
![image](https://github.com/OneBusAway/onebusaway-ios/assets/50642934/d325f91e-08d3-420a-960e-a6fdd09adbe2)
![image](https://github.com/OneBusAway/onebusaway-ios/assets/50642934/d00d8516-48fe-41e8-954f-bbc56184bfca)

Here it is on Android, from the video...
<img width="325" alt="image" src="https://github.com/OneBusAway/onebusaway-ios/assets/50642934/70170071-0ed0-40ea-80d5-adf91693d73e">

**Comment by aaronbrethorst** [comment]
@Macintosh-Fan tap on the "Region" table item.

**Comment by Macintosh-Fan** [comment]
![image](https://github.com/OneBusAway/onebusaway-ios/assets/50642934/3a948f53-d5df-43d1-9c37-a190719a3af6)

**Comment by Macintosh-Fan** [comment]
![image](https://github.com/OneBusAway/onebusaway-ios/assets/50642934/a4bdc403-3f82-4ff8-bf30-bdf70b7a0ec6)

**Comment by aaronbrethorst** [comment]
@Macintosh-Fan "New Custom Region" is the option you're looking for.

**Comment by Macintosh-Fan** [comment]
GUI layout difference. Thank you!
