### ISSUE TITLE
Seattle Light Rail Arrival/Departures Not Working Correctly 

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#706]
Pull up any of the light rail stops in Seattle (what is now referred to as the `1 Line`).

Expected: Arrivals and departures are shown.

Actual: Data error :(

The data error is being caused by issues decoding `TimeWindow` objects in `ServiceAlert`. Commenting out `activeWindows` and `publicationWindows` in `ServiceAlert` (and replacing them with empty values) resolves the issue. See screenshot below under "TimeWindow"

Here's an example URL that is not functioning in the app: https://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-stop/40_501.json?minutesAfter=35&minutesBefore=5&version=2&app_uid=603A1221-8D00-489B-A44A-6DDB9D55F4BE&app_ver=23.4.0&key=org.onebusaway.iphone

For comparison, here's one that's working fine (it's for a bus line, not light rail): https://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-stop/1_11570.json?minutesAfter=35&minutesBefore=5&version=2&key=org.onebusaway.iphone&app_uid=603A1221-8D00-489B-A44A-6DDB9D55F4BE&app_ver=23.4.0

![image](https://github.com/OneBusAway/onebusaway-ios/assets/2254/cf30bfc1-388f-461a-8cea-cbabb7576c1c)

## TimeWindow

<img width="870" alt="image" src="https://github.com/OneBusAway/onebusaway-ios/assets/2254/bd37e882-7376-4530-b399-5b3177b3c0ea">

**Comment by aaronbrethorst** [comment]
Hey @ualch9 - ever seen anything like this before? Ostensibly it's been caused by some sort of data change in the Light Rail data, but I haven't been able to find anything glaring yet.

**Comment by aaronbrethorst** [comment]
Found it. One of the `activeWindow`s is missing a `to` date.

**Comment by petedussin** [comment]
@aaronbrethorst is the missing TimeWindow.to an actual data issue? Is it required upstream in the GTFS, or is it required to be populated in the OBA API response?  Or is it a case that the IOS code needed to handle and is now fixed (Android didn't seem to break, but I can't remember if it even does alerts) Trying to get a handle on where the data issue is. Thanks for your effort here!

**Comment by aaronbrethorst** [comment]
@petedussin It's an actual data issue in the sense that a data field that the iOS expected would always exist no longer existed, and that broke the iOS app's ability to render the 1 Line. The Android app was more resilient with its data expectations, apparently.
