### ISSUE TITLE
Build Failed (fresher to Xcode)

### ISSUE THREAD

**Issue by shrudge** [OneBusAway/onebusaway-ios#717]
### I tried to setup and build this project into my machine but it shows package fetching errors 
<img width="273" alt="OBAKit 1 issue" src="https://github.com/OneBusAway/onebusaway-ios/assets/74920401/1f5f513b-8025-4938-9c79-5b0ee6879b9a">

I am very new to the swift development in terms of open source projects, can anybody help out, thanks !

**Comment by ualch9** [comment]
Hi @shrudge, what version of Xcode are you running? 

You can find this by going to <kbd>Xcode</kbd> in the toolbar and selecting `About Xcode`.
![Screenshot 2024-03-12 at 10 50 56 PM](https://github.com/OneBusAway/onebusaway-ios/assets/22162410/1e8bc2d9-3fef-4362-b22b-c697fc78be37)
![Screenshot 2024-03-12 at 10 51 19 PM](https://github.com/OneBusAway/onebusaway-ios/assets/22162410/2c6ce681-2a4f-45db-b3b9-8d8ed7feda55)

**Comment by ualch9** [comment]
Actually, I encountered a similar SPM issue after updating Xcode last night. Try deleting derived data.

**Comment by shrudge** [comment]
> Actually, I encountered a similar SPM issue after updating Xcode last night. Try deleting derived data.

i deleted the derived data and tried to build it, now its showing 
<img width="108" alt="image" src="https://github.com/OneBusAway/onebusaway-ios/assets/74920401/f64b772a-4f5c-44a7-b8ef-36a13b5cd1df">
i am running on xcode 15.3, I opened the OBAkit.xcodeproj as mentioned in the get started instructions, i am really sorry if i am making a big rookie mistake here...

**Comment by Himindu-Kularathne** [comment]
it is version incompatible, check [this](https://github.com/Yummypets/YPImagePicker/issues/789#issuecomment-1605655190)

**Comment by Pahul-Sidhu** [comment]
<img width="272" alt="Screenshot 2024-03-22 at 3 03 47 PM" src="https://github.com/OneBusAway/onebusaway-ios/assets/97401471/eea2ab56-c43b-432e-8b37-44d18211ee35">

I am having all these issues while building. Would really appreciate the help ? My Xcode version is 15.0.1.

**Comment by ualch9** [comment]
Hi everyone, please make sure you run `scripts/generate_project` and clear derived data before opening `OBAKit.xcodeproj`. I need more information to understand the issues you are having. If you are still having issues, please go to the Report Navigator, navigate to the most recent Build failure, and include a full screenshot or "Export..." the build logs.

<img width="1188" alt="Screenshot 2024-03-23 at 9 18 29 AM" src="https://github.com/OneBusAway/onebusaway-ios/assets/22162410/3decc67b-bc3f-4b84-b095-293ae95da70a">
