### ISSUE TITLE
Custom regions should not use the ObacoService

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#722]
As demonstrated by Hilmy in #719 (see https://github.com/OneBusAway/onebusaway-ios/issues/719#issuecomment-2023171586), errors occur when a custom region tries to access Obaco services. The ObacoService should be disabled for any custom region.

**Comment by manu-r12** [comment]
Hey, can you provide me the steps to do this?

**Comment by aaronbrethorst** [comment]
Fixed in #758
