### ISSUE TITLE
Arrival time is frequently wrong for 28X bus in Seattle 

### ISSUE THREAD

**Issue by aawiseman** [OneBusAway/onebusaway-ios#725]
The 28X arrival time in Seattle is often way off. For example in this case the bus has two more stops to go before this stop, but still says one minute, not sure how that’s determined. Maybe it’s taken from the city’s feed? 
![IMG_6485](https://github.com/OneBusAway/onebusaway-ios/assets/5025092/815ce314-4932-494c-9350-65d55e6915a4)

**Comment by aaronbrethorst** [comment]
@aawiseman Yeah, the data all comes from KC Metro by way of Sound Transit. You can (and absolutely should) reach out to them at onebusaway@soundtransit.org with this information.
