### ISSUE TITLE
Unable to report a problem with a vehicle at a stop

### ISSUE THREAD

**Issue by Eptin** [OneBusAway/onebusaway-ios#727]
When I have any field filled out, I receive this error upon attempting to submit: "The data couldn't be read because it is missing."

![image](https://github.com/OneBusAway/onebusaway-ios/assets/6963622/c25f05b1-16df-44bf-8b4b-7cd33e16d2d8)

It's only when I remove the additional comment, disable the "On the vehicle" toggle, and remove the Vehicle ID text that I'm finally able to submit the report.

**Comment by Eptin** [comment]
Found on OneBusAway v24.1.0 on iOS 17.5.1 (iPhone 12 Mini while on Google Fi cellular)

**Comment by aaronbrethorst** [comment]
Thank you for the report @Eptin!

**Comment by aaronbrethorst** [comment]
We're going to fix this with #750
