### ISSUE TITLE
Stop display 

### ISSUE THREAD

**Issue by Kaelid03** [OneBusAway/onebusaway-ios#728]
When you click on a stop number it doesn’t Display any scheduled times. Almost like the route is out of service.

**Comment by aaronbrethorst** [comment]
Hi @Kaelid03 - can you include a screenshot?

**Comment by Kaelid03** [comment]
![IMG_0649](https://github.com/OneBusAway/onebusaway-ios/assets/170976416/cf2c8429-209c-47f1-80ad-7cf3545ade2b)

**Comment by Kaelid03** [comment]
It’s been giving me this prompt like the buses are out of service for 2 days but it’s all the stops and the routes are in service

**Comment by aaronbrethorst** [comment]
Where are you located, @Kaelid03?

**Comment by Kaelid03** [comment]
Spokane WA.  I moved here about a year and a half ago from the Seattle area and it’s worked since I’ve lived  in Spokane up until now.  It automatically registers my location. I am a little unsure why it’s not working now.

**Comment by aaronbrethorst** [comment]
@Kaelid03 I've been investigating and it looks like a data issue on the Spokane Transit Authority OBA server. I have reported it to them and hopefully they will get back to you soon. sorry for the trouble!

**Comment by aaronbrethorst** [comment]
@Kaelid03 just heard back from the STA folks. They've fixed the data issues and you should be all set.
