### ISSUE TITLE
Support for dark, tinted app icons

### ISSUE THREAD

**Issue by ScottSmith95** [OneBusAway/onebusaway-ios#746]
It would be nice to see OBA support dark/tinted app icons on iOS 18+.

**Comment by manu-r12** [comment]
#### I've tried creating dark, tinted app icon. Let me know your thoughts : )

Preview:

https://github.com/user-attachments/assets/93d752ff-06ef-405c-9005-026c25147cc0

**Comment by aaronbrethorst** [comment]
Looks cool, @manu-r12. open a PR! :)

**Comment by aaronbrethorst** [comment]
Fixed in #759
