### ISSUE TITLE
Fix deprecation: 'onChange(of:perform:)' was deprecated in iOS 17.0

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#762]
There are several places in our codebase where we're now seeing deprecation warnings about `'onChange(of:perform:)'` being deprecated.

Expectation:

Use `onChange` with a two or zero parameter action closure instead to silence these deprecation warnings.

Locations:

- [ ] ./OBAKit/Controls/Navigation/RenamableNavigationTitle.swift:37:14 
- [ ] ./OBAKit/Controls/Navigation/RenamableNavigationTitle.swift:40:14 
- [ ] ./OBAKit/Donations/DonationLearnMoreView.swift:79:10 
- [ ] ./OBAKit/Onboarding/RegionPicker/RegionPickerView.swift:82:10

**Comment by manu-r12** [comment]
new problems 👀 ,  got this
